### ISSUE TITLE
Feature: add support for Cilium

### ISSUE THREAD

**Issue by nvibert** [deggja/netfetch#48]
Good idea behind your tool. Consider looking at Cilium as well as Cilium Network Policies are becoming very commonly used.

https://docs.cilium.io/en/stable/security/policy/

**Comment by deggja** [comment]
Example endpointSelector netpol for Cilium:

```yaml
apiVersion: "cilium.io/v2"
kind: CiliumNetworkPolicy
metadata:
  name: "l3-rule"
spec:
  endpointSelector:
    matchLabels:
      role: backend
  ingress:
  - fromEndpoints:
    - matchLabels:
        role: frontend
```

Example cluster wide policy that wont have any connection to namespaces.

```yaml
apiVersion: "cilium.io/v2"
kind: CiliumClusterwideNetworkPolicy
metadata:
  name: "clusterwide-policy-example"
spec:
  description: "Policy for selective ingress allow to a pod from only a pod with given label"
  endpointSelector:
    matchLabels:
      name: leia
  ingress:
  - fromEndpoints:
    - matchLabels:
        name: luke
```

As far as I am concerned, these are the two scenarios we need to support. A node selector policy will also use the endpointSelector and can only be used with clusterwide policies.
