### ISSUE TITLE
Bug: Network policies with same name are displayed incorrectly

### ISSUE THREAD

**Issue by kyrbrbik** [deggja/netfetch#91]
When you create a multiple network policies with the same name but in different namespaces they should be limited to the namespace but they are shown incorrectly in the cluster map. 

Example policy

```
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: allow-unknown-app-5000-tcp-nfpol
  namespace: test
spec:
  podSelector:
    matchLabels: {}
  policyTypes:
    - Ingress
    - Egress
  ingress:
    - from: []
      ports:
        - protocol: TCP
          port: 5000
  egress:
    - to:
        - ipBlock:
            cidr: 0.0.0.0/0
```

If there is another policy with the same name for example in namespace test2 all of the pods across the two namespaces that are withing the policy scope will be linked in the cluster map to only one of these policies.
